name: ISO build

on:
  workflow_dispatch:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@v14
    - uses: DeterminateSystems/magic-nix-cache-action@v8
    - name: Build Custom ISO
      run: |
        nix build .#iso --accept-flake-config
        mkdir iso || true
        ISO=$(head -n1 result/nix-support/hydra-build-products | cut -d'/' -f6)
        sudo mv "./result/iso/${ISO}" iso/${ISO}
        sha256sum "iso/${ISO}" > "iso/${ISO}.sha256"
        sed -i -r "s/ .*\/(.+)/  \1/g" "iso/${ISO}.sha256"
        ls -la
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for artefact in ./"iso/*"; do
          gh release upload "${{ github.ref }}" "${artefact}" --clobber
        done
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ "$(gh release view "${{ github.ref }}" --json assets --template '{{len .assets}}')" -lt 0 ]; then
          exit 1
        fi
        gh release edit "${{ github.ref }}" --draft=false
