name: "Build ISO"

on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-iso
  cancel-in-progress: true

jobs:
    ISO:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: install nix
      uses: DeterminateSystems/nix-installer-action@main
      #with:
      #github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#iso
    - name: Upload ISO as artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
          name: ISO
          path: |
            ./result/iso/*.iso
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
