name: "Nix flake cache checker"

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      #- uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix run flake checker`
        run: nix run github:DeterminateSystems/flake-checker --extra-experimental-features "nix-command flakes"
